### PR TITLE
allow to set widget / version tag

### PR DESCRIPTION
**Pull request by godrei**
This PR introduces a new input: `version`, which allows users to set the widget / version property of the config.xml file.
Other then that a small update also introduced in the bitrise.yml, if you put a config.xml file in the _tmp dir you can play with the step during development.

### CODE REVIEW

**Review by goscore — APPROVED** [review]
Excelente Commit!

**Comment by the-nicolas** [comment]
Thats great, was looking exactly for that. Why not merged yet?

**Comment by mouhamed** [comment]
Great PR I was about to submit the same thing!

**Comment by fb64** [comment]
Does it's possible to merge this PR or do we need to fork the project ?

**Comment by Ionaru** [comment]
@blackjid Any chance this can be merged?

**Comment by blackjid** [comment]
Sorry, we are not using this step a lot...
I don't know why I didn't see all other comments 😁

**Comment by blackjid** [comment]
released on https://github.com/platanus/bitrise-step-cordova-config/releases/tag/0.0.4
I don't expect to maintain this step any longer as we moved away from cordova
If anyone wants to maintain a fork you are very welcomed.

**Pull request merged**
